### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by joemphilips** [NCCJapan/cisCall5_doc#1]
以下の作業をこちらでやっていきます。
@monagai 

- [ ] `install.md` にquickstart.mdのデータに関する説明を移す。
- [ ] `virtual box` の使用を強く推奨する旨を書く
- [ ] `quick_start.md` をvirtual box内でやることを前提にした書き方に直す

**Comment by joemphilips** [comment]
> quick_start.md をvirtual box内でやることを前提にした書き方に直す

これはimageの作成が終わってからにしたいと思いますので、終了したらお教えください。
@monagai

**Comment by monagai** [comment]
> これはimageの作成が終わってからにしたいと思いますので、終了したらお教えください。

承知しました．

資源の用意の仕方は，どうしますか?
  - パネルはどれを使います? SURESELECT2?(0471501_Covered?)
  - パネル名(グループ名) → うちの中ではSURESELECT2とか言っていますが…このままで良いですか?
  - インターネット上のリソースは，そのファイル名はそのままにして，
    symlinkで名前をcisCall5向けに合わせると思っていますが，それで良いですか?

**Comment by monagai** [comment]
実行用sheも用意しておかないと、ですよね。

**Comment by monagai** [comment]
readmeは、ある程度固まったら、版を決めてレビュー+修正(のたぶん何サイクルかの繰り返しで)をきちんと回してほしいです。(サイクルは細かくても良いので五月雨的にずるずる直さずに)

**Comment by monagai** [comment]
以下のようなdir構成を考えています．こうした方が良いなどあれば言ってください．
+ /home/cisusr/
  + cisCall/
    + cisFusion5/  : bin
    + cisMuton5/   : bin
    + cisCton7/    : bin
    + resource/       : サンプル以外の資源．インターネット資源は元ファイル名のまま
    + run_cisFusion5/ : cisFusion5実行環境．resourceはslymlink
    + run_cisMutonn5/ : cisFusion5実行環境．resourceはslymlink
    + run_cisCton7/   : cisFusion5実行環境．resourceはslymlink

**Comment by monagai** [comment]
> インターネット上のリソースは，そのファイル名はそのままにして， symlinkで名前をcisCall5向けに合わせると思っていますが，それで良いですか?
黒坂さんは、頭にhuman_hg19というprefixを付けており、これが分かりやすそうなので踏襲します。

**Comment by joemphilips** [comment]
dir構成はおおむね問題ないと思いますが、一点だけ`cisFusion`, `cisMuton`, `cisCton` などというようにバージョン名を付けないディレクトリ名でよいと思います。

**Comment by monagai** [comment]
> dir構成はおおむね問題ないと思いますが、一点だけcisFusion, cisMuton, cisCton などというようにバージョン名を付けないディレクトリ名でよいと思います。
ここは私も迷いました(今後改版していくことを考えた時にどっちがいいのか)。そうましょう。

**Comment by monagai** [comment]
readmeの入力資源については，レビューの際に私もcheckするようにしますが，
以下のような，注意点があります．備忘もかねて上げておきます．

+ cisCall5:
  - gz のままのものと，txt のままで配置するものがある
  - 元が*.txt でも，拡張子なしで配置するものがある
      (genomicSuperDups.txt，rmsk, simpleRepeatに注意)
  - MAX_PROCESSの説明を忘れそう．注意
+ cisCall7
  - target_fusion.txtの説明に注意(ファイル名固定．dirは?)
  - refGene.txtは，gunzipしておかないとダメ Cf. cisCall5はgz
  - wgEncodeDukeMapabilityUniqueness20bp.bigWigの説明に注意(ファイル名固定．dirは?)
  - ciscall.configに注意
  - bedは，<group名>.bedで配置し，コマンドラインでの指定方法は，<group名>の部分のみ．
    cf. cisCall5は，<group名>.target.bed

**Comment by monagai** [comment]
宮本さん

INSTALL.mdの上半分だけで，下記指摘あり．直接直してもいいならそうするけど．

+ Required Environment:
  - "installation of cisCall"
    - タイトルと説明が合わない．ここは環境設定ですよね．
  - R : 
    - Cton5とCton7あわせると私は3.2.2でしか確認取っていません．(3.1.1で動くのかわからない)
    - .configureで--enable-R-shlib --with-libpngオプションつけてmake要
    - cluster", "coin", "RPMM", "VGAM", "exactRankTests" 要．(私が環境作成で指定しているのはこれだけ)
  - Python: 
    -  .configureで --enable-R-shlib --with-libpng オプションつけてmake要
    - six，scipy，numpy，rpy2要 
  - Perl: 
    - 版数は? V5以上とかでも良いのかもしれませんが．
    - Math::CDF必須

+ Required Packages
  - CutAdapt, Cython, Varscan，Annovar不要
  - BWAとSamtoolsは，cisFusion5，cisMutonに含まれているのでインストール不要．(ここに書いておく必要はあるが)
  - cisXXX別にしない方がいいです．(だったら，RとかもPyhon3自体も分けないと変)

**Comment by monagai** [comment]
> --enable-loadable-sqlite-extensions
つまり、sqliteも入れてってことですね。CentOS6.8-minimalから今入れているのは下記。どこまで書くかな。
(git wget gcc gcc-c++ gcc-gfortran readline-devel zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel tk-devel java-1.8.0-openjdk libpng-devel cairo-devel pango pango-devel
perl-CPAN perl-YAML

**Comment by joemphilips** [comment]
一応最初のコメントをチェック形式にアップデートしました。作業が完了した時点でチェックしていってください。

必要に応じて新しいTODOを挙げておいていただいても :ok: です。

**Comment by monagai** [comment]
ctonのサンプル作って、mutonも以前決めた名前(PANEL_FOR_TESTとか)にrenameしていてハタと気づいたのですが、cisCall5のGUIを使ってパラメタをsetさせる仕様ではなく、お仕着せのparamを使わせるのであればparam下のfile名をrenameしないといけません。忘れそうなのであげておきます
※他から転記

**Comment by monagai** [comment]
これも忘れないうちに。。。
"FG"とか"BG"とかいうのは、注釈無しで使って一般的に理解されるものなんでしょうか?
※もしそうでなければ、使わないのがベスト、使うなら最初に説明を入れる必要あり

**Comment by joemphilips** [comment]
> "FG"とか"BG"とかいうのは、注釈無しで使って一般的に理解されるものなんでしょうか?

ファイルの説明表に一言あるので、多分伝わるとは思いますが、一応くどめに言っておいた方が良いでしょうね。

**Comment by monagai** [comment]
私もうっかりしていて、cton公開サンプルでもcton.mdでも入れ忘れているのですが、max processの説明を入れておくべきかと。備忘メモで上げおきます

**Comment by joemphilips** [comment]
> 私もうっかりしていて、cton公開サンプルでもcton.mdでも入れ忘れているのですが、max processの説明を入れておくべきかと。備忘メモで上げおきます

メモとして挙げておくよりもPRで挙げてしまった方が忘れづらくて良いのでは
(ただのsuggestionですのでお任せしますが)

**Comment by monagai** [comment]
すみません、"PR"が何のことかわからず。。。

**Comment by joemphilips** [comment]
Pull Requestです

**Comment by monagai** [comment]
ええっと、それって1件ずつ1個のPRにするということ?

**Comment by joemphilips** [comment]
そうです。

**Comment by monagai** [comment]
申し訳ないのですが、やり方がよくわからず。異なるブランチ間の比較でないとPRできないような。よくわかていなくてすみません。見落としそうだというならissueで上げるならできますが

**Comment by joemphilips** [comment]
新しいブランチを切って、そこからmasterに対してPRするという意味です。
( @monagai さんが やりやすいやり方でやるのがベストですので、あんまり気にしないでください。)

**Comment by monagai** [comment]
> 新しいブランチを切って、そこからmasterに対してPRするという意味です。
スミマセン了解です(汗) 手がかかることで申し訳ない。
(いや、そうかなとはちょっと思ったんだけど)

**Comment by monagai** [comment]
cisCall5のMAX_PROCESSの説明が必要です(とりあず備忘でここに上げおきますが)
